name: Compile Flix Drone Firmware

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # v3 မှ v4 သို့ မြှင့်ထားသည်

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install ESP32 Board Core
      run: |
        arduino-cli core update-index --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
        arduino-cli core install esp32:esp32 --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json

    - name: Install Exact Project Libraries
      run: |
        arduino-cli lib install "FlixPeriph"
        arduino-cli lib install "MAVLink"@2.0.25

    - name: Compile Code for ESP32-C3
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32c3 --output-dir ./build "./main"

    - name: Upload Compiled Binary Artifact
      uses: actions/upload-artifact@v4 # v3 မှ v4 သို့ မြှင့်ထားသည် (Error ကျော်ဖြတ်ရန်)
      with:
        name: flix-esp32c3-binary
        path: ./build/*.bin
        
