name: Build Flix Drone Firmware

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh

    - name: Setup ESP32 Board Core
      run: |
        arduino-cli core update-index --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
        arduino-cli core install esp32:esp32 --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json

    - name: Install Flix Project Libraries
      run: |
        arduino-cli lib install "FlixPeriph"
        arduino-cli lib install "MAVLink"@2.0.25

    - name: Build firmware for ESP32-C3
      run: |
        # ညီလေးပြထားတဲ့ ဖိုင်နာမည်အမှန်အတိုင်း flix_esp32C3.ino လို့ ကွက်တိပြင်ထားပါတယ်
        arduino-cli compile --fqbn esp32:esp32:esp32c3 --output-dir ./build_c3 "./main/flix_esp32C3.ino"

    - name: Build firmware for ESP32-S3
      run: |
        # S3 အတွက်ပါ လမ်းကြောင်းမှန်အောင် တစ်ခါတည်း ပြင်ထားပေးခြင်း
        arduino-cli compile --fqbn esp32:esp32:esp32s3 --output-dir ./build_s3 "./main/flix_esp32C3.ino"

    - name: Upload ESP32-C3 Binary
      uses: actions/upload-artifact@v4
      with:
        name: flix-esp32c3-firmware
        path: ./build_c3/*.bin

    - name: Upload ESP32-S3 Binary
      uses: actions/upload-artifact@v4
      with:
        name: flix-esp32s3-firmware
        path: ./build_s3/*.bin
        
