name: Build Flix Drone Firmware

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh

    - name: Setup ESP32 Board Core
      run: |
        arduino-cli core update-index --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
        arduino-cli core install esp32:esp32 --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json

    - name: Install Flix Project Libraries
      run: |
        arduino-cli lib install "FlixPeriph"
        arduino-cli lib install "MAVLink"@2.0.25

    - name: Rename Folder to Match Sketch Name
      run: |
        # Arduino CLI ၏ စည်းကမ်းနှင့် ကိုက်ညီစေရန် ညီလေး၏ main ဖိုဒါကို flix_esp32C3 ဟု ခေတ္တ နာမည်ပြောင်းပေးခြင်း
        mv ./main ./flix_esp32C3

    - name: Build firmware for ESP32-C3 Only
      run: |
        # နာမည်တူသွားပြီဖြစ်၍ အမှားအယွင်းမရှိ တိုက်ရိုက် Compile အောင်မြင်တော့မည်ဖြစ်သည်
        arduino-cli compile --fqbn esp32:esp32:esp32c3 --output-dir ./build_c3 "./flix_esp32C3"

    - name: Upload ESP32-C3 Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: flix-esp32c3-firmware
        path: ./build_c3/*.bin
        
